### ISSUE TITLE
Date-time-convert.cc Issue

### ISSUE THREAD

**Issue by Bmcaleer1** [esilver-uvm/Left-Group-VERSO#24]
The program is intended to convert a date string from "YYYY-MM-DD HH:MM:SS" format to "MM/DD/YYYY HH:MM:SS" format and print it. However, it contains a memory memory leak issue.

Steps to Reproduce

1- First step to reproduce the issue/bug: Compile and run the provided code.
2- Second step to reproduce the issue/bug: Observe the console output and look at system memory usage.
3-  Third step to reproduce the issue/bug: Check for any errors, warnings, or unusual behavior.

 Expected Behavior: The program should output the formatted date (03/17/2022 10:45:30) in the console. The program should allocate memory efficiently and release it at the end of execution.

Actual Behavior: The date is formatted and printed as expected. The program allocates a large amount of memory with malloc(120000000), which is a crazy amount of memory and may lead to a crash.

Screenshots
NO

Additional Information:
Operating System:  Windows 11
Browser: Chrome
Version: CLion version 2024.2.1
Other relevant information: No cleanup is performed for the allocated memory, which could cause memory leaks.

Possible Solution:
Replace malloc(120000000) with a smaller, necessary allocation or remove it since its not needed Use 'delete' to release allocated memory to prevent memory leaks.

Related Issues
N/A

Priority
Medium

Reproducibility
Always

Impact
Medium - The high memory allocation is unnecessary and can cause instability on systems with limited memory.

**Comment by esilver-uvm** [comment]
Hahaha what's wrong with you. Just get more ram. Closing.

**Comment by hcussatt** [comment]
Removed memory allocation to fix issue.
