### ISSUE TITLE
rgb_to_hex.py Bug Report

### ISSUE THREAD

**Issue by hcussatt** [esilver-uvm/Left-Group-VERSO#25]
Invalid RGB conversion along with crashing above certain input threshold.

Steps to Reproduce

1.) Enter any RGB value
2.) Values above 122 crash program, values below 122 are incorrect conversions

Expected Behavior A: Return a valid hex value equivalent to entered RGB value

Actual Behavior A: Returns hex value different from entered RGB value

Additional Information

Operating System: macOS Sonoma 14.3
Browser: Google Chrome
Version: 129.0.6668.100
Any other relevant information
Possible Solution If you have any suggestions for a possible solution, please include them here.

High priority issue, program does not work without necessary fixes

Bug is completely and consistently reproducible.

High impact bug, as program does not work without necessary fixes

**Comment by esilver-uvm** [comment]
Fixed. *2 present in code.
