### ISSUE TITLE
Memory Leak in remove_duplicates.cc

### ISSUE THREAD

**Issue by esilver-uvm** [esilver-uvm/Left-Group-VERSO#27]
A float pointer on line 22 of remove_duplicates.cc causes a needless memory leak. 

**Steps to Reproduce**
1. Compile and run the executable.
2. A memory leak occurs, 120020123 bytes are allocated and never released.

**Expected Behavior**
We expect the program to remove duplicates from a vector.

**Actual Behavior**
Instead, 120020123 bytes are allocated, grinding my device to a halt. 

**Additional Information**
My OS is macOS Sonoma 14.6.1
My Browser is Firefox 132.0.1
The Version is unversioned.

**Possible Solution**
Remove the memory allocation. Nothing is even put in the float pointer. Floats cannot even conceivably be that big. Wikipedia isn't that big. My collection of movies isn't that big. It is a void and it is needless.

**Related Issues**
Some wiseguy did the exact same thing in datetime_convert.cc

**Priority**
High. It makes the program unusable.

**Reproducibility**
It's guaranteed to happen every time the function is called due to unsafe pointers so long as compilation occurs without optimization.

**Impact**
It renders the program unusable.

**Comment by JayYarlott** [comment]
Have you tried purchasing more RAM, or perhaps visiting https://downloadmoreram.com ?

**Comment by esilver-uvm** [comment]
BLOWING UP MY DANG EMAILS

On Nov 12, 2024, at 14:16, JayYarlott ***@***.***> wrote:

﻿

Have you tried purchasing more RAM, or perhaps visiting https://downloadmoreram.com ?

**Comment by Bmcaleer1** [comment]
fixed float* thing = malloc(120020123); Now memory allocation is working
